# Generated by Django 4.2.4 on 2023-08-30 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='project_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 19, 13, 21, 363335)),
        ),
    ]
